### PR TITLE
Update build.yml - Fixes Action Workflow

### PR DESCRIPTION
**Pull request by SekouDiaoNlp**
use ${{ env.PACKAGE_NAME }} and ${{ env.MAIN_MODULE }}

### CODE REVIEW

**Comment by SekouDiaoNlp** [comment]
hmmm...

ther is till that `IndexError: list index out of range`.

**Review by juancarlospaco — APPROVED** [review]

**Comment by juancarlospaco** [comment]
> hmmm...
> 
> there is till that `IndexError: list index out of range`.

But that error is from Nimporter, not from this repo...

**Comment by SekouDiaoNlp** [comment]
> > hmmm...
> > there is till that `IndexError: list index out of range`.
> 
> But that error is from Nimporter, not from this repo...

Ah yes, that's true.

**Comment by SekouDiaoNlp** [comment]
I'll merge then.

**Comment by juancarlospaco** [comment]
> Ah yes, that's true.

I dont know what to do about Nimporter.

Maybe try to fix it?.

Maybe strip it to the bare basics and bundle it in this repo?.

**Comment by SekouDiaoNlp** [comment]
> > Ah yes, that's true.
> 
> I dont know what to do about Nimporter.
> 
> Maybe try to fix it?.
> 
> Maybe strip it to the bare basics and bundle it in this repo?.

I can investigate more in depth tomorrow

**Pull request merged**
